" Vim-Plug
call plug#begin('~/.nvim/plugged')

" SuperTAB 
Plug 'ervandew/supertab'

" Completion
Plug 'Valloric/YouCompleteMe'

" NeoSnippet
Plug 'SirVer/ultisnips'
Plug 'honza/vim-snippets'

" NerdCommenter & NerdTree
Plug 'scrooloose/nerdtree'
Plug 'scrooloose/nerdcommenter'

" Tern (JS-Completion)
Plug 'marijnh/tern_for_vim'

" Fuzzy File Search
Plug 'kien/ctrlp.vim'

" indentLine
Plug 'Yggdroot/indentLine'

" Tag closer
Plug 'jiangmiao/auto-pairs'
Plug 'alvan/vim-closetag'

" HTML Editing
Plug 'Valloric/MatchTagAlways'

" Airline
Plug 'bling/vim-airline'

" Git integration
Plug 'tpope/vim-fugitive'

" Highlighting
Plug 'tikhomirov/vim-glsl'
Plug 'evidens/vim-twig'
Plug 'StanAngeloff/php.vim'
Plug 'cakebaker/scss-syntax.vim'
Plug 'JulesWang/css.vim' 
Plug 'pangloss/vim-javascript'

Plug 'altercation/vim-colors-solarized'

call plug#end()

" CTRL-P
let g:ctrlp_user_command = {
  \ 'types': {
    \ 1: ['.git', 'cd %s && git ls-files --cached --exclude-standard --others'],
    \ 2: ['.hg', 'hg --cwd %s locate -I .'],
    \ },
  \ 'fallback': 'find %s -type f'
  \ }

" Closetag.vim
let g:closetag_filenames = "*.html,*.xhtml,*.phtml"

" Highighting Options
" -------------------

syntax on

" Squirrel
au BufNewFile,BufRead *.nut setf squirrel

" Indent Line Config
let g:indentLine_color_term = 239
let g:indentLine_color_gui = '#A4E57E'
let g:indentLine_char = '¦'

" Angelscript Syntax
au BufRead,BufNewFile *.as set syntax=cpp "angelscript
au BufRead,BufNewFile *.angelscript set syntax=cpp "angelscript

" GLSL syntax
au BufRead,BufNewFile *.vs set syntax=glsl
au BufRead,BufNewFile *.fs set syntax=glsl

" Airline Config
let g:airline_detect_modified=1
let g:airline_detect_paste=1
let g:airline_inactive_collapse=1

" YCM + UltiSnips
let g:ycm_key_list_select_completion=['<C-n>', '<Down>']
let g:ycm_key_list_previous_completion=['<C-p>', '<Up>']

let g:UltiSnipsExpandTrigger="<Tab>"
let g:UltiSnipsJumpForwardTrigger="<Tab>"                                           
let g:UltiSnipsJumpBackwardTrigger="<S-Tab>"

if has('gui_running')
    set guifont=Inconsolata\ for\ Powerline\ 12

    set background=dark
    colorscheme solarized
endif

" Set line numbers
set number

" Indention
" ---------

filetype plugin indent on

" Smartindention Configs
set smartindent
set tabstop=4
set shiftwidth=4
set expandtab

" Mappings
" --------
" Terminal mappings: ALT+Direction
" HJKL
tnoremap <A-h> <C-\><C-n><C-w>h
tnoremap <A-j> <C-\><C-n><C-w>j
tnoremap <A-k> <C-\><C-n><C-w>k
tnoremap <A-l> <C-\><C-n><C-w>l
nnoremap <A-h> <C-w>h
nnoremap <A-j> <C-w>j
nnoremap <A-k> <C-w>k
nnoremap <A-l> <C-w>l

tnoremap <Esc> <C-\><C-n>

" Set the CTRL+S command
noremap <silent> <C-S>          :update<CR><ESC>
vnoremap <silent> <C-S>         <C-C>:update<CR><ESC>
inoremap <silent> <C-S>         <C-O>:update<CR><ESC>
