" Vim-Plug
call plug#begin('~/.nvim/plugged')

" SuperTAB 
Plug 'ervandew/supertab'

" Completion
Plug 'Shougo/neocomplete.vim'
Plug 'Shougo/vimproc.vim'
Plug 'osyo-manga/vim-marching'

" NeoSnippet
Plug 'Shougo/neosnippet.vim'
Plug 'Shougo/neosnippet-snippets'

" NerdCommenter & NerdTree
Plug 'scrooloose/nerdtree'
Plug 'scrooloose/nerdcommenter'

" Tern (JS-Completion)
Plug 'marijnh/tern_for_vim'

" Fuzzy File Search
Plug 'kien/ctrlp.vim'

" indentLine
Plug 'Yggdroot/indentLine'

" Tag closer
Plug 'jiangmiao/auto-pairs'

" Airline
Plug 'bling/vim-airline'

" Git integration
Plug 'tpope/vim-fugitive'
Plug 'vim-gitgutter'

" Highlighting
Plug 'tikhomirov/vim-glsl'
Plug 'evidens/vim-twig'
Plug 'StanAngeloff/php.vim'
Plug 'cakebaker/scss-syntax.vim'
Plug 'JulesWang/css.vim' 
Plug 'pangloss/vim-javascript'


call plug#end()

" CTRL-P
let g:ctrlp_user_command = {
  \ 'types': {
    \ 1: ['.git', 'cd %s && git ls-files --cached --exclude-standard --others'],
    \ 2: ['.hg', 'hg --cwd %s locate -I .'],
    \ },
  \ 'fallback': 'find %s -type f'
  \ }

" Disable AutoComplPop.
let g:acp_enableAtStartup = 0
" Use neocomplete.
let g:neocomplete#enable_at_startup = 1
" Use smartcase.
let g:neocomplete#enable_smart_case = 1
" Set minimum syntax keyword length.
let g:neocomplete#sources#syntax#min_keyword_length = 3
let g:neocomplete#lock_buffer_name_pattern = '\*ku\*'

" Highighting Options
" -------------------

syntax on

" Squirrel
au BufNewFile,BufRead *.nut setf squirrel

" Indent Line Config
let g:indentLine_color_term = 239
let g:indentLine_color_gui = '#A4E57E'
let g:indentLine_char = '¦'

" Angelscript Syntax
au BufRead,BufNewFile *.as set syntax=cpp "angelscript
au BufRead,BufNewFile *.angelscript set syntax=cpp "angelscript

" GLSL syntax
au BufRead,BufNewFile *.vs set syntax=glsl
au BufRead,BufNewFile *.fs set syntax=glsl

" Airline Config
let g:airline_detect_modified=1
let g:airline_detect_paste=1
let g:airline_inactive_collapse=1

" Indention
" ---------

filetype plugin indent on

" Smartindention Configs
set smartindent
set tabstop=4
set shiftwidth=4
set expandtab

" Mappings
" --------
" Terminal mappings: ALT+Direction
" HJKL
tnoremap <A-h> <C-\><C-n><C-w>h
tnoremap <A-j> <C-\><C-n><C-w>j
tnoremap <A-k> <C-\><C-n><C-w>k
tnoremap <A-l> <C-\><C-n><C-w>l
nnoremap <A-h> <C-w>h
nnoremap <A-j> <C-w>j
nnoremap <A-k> <C-w>k
nnoremap <A-l> <C-w>l

tnoremap <Esc> <C-\><C-n>

" Set the CTRL+S command
noremap <silent> <C-S>          :update<CR><ESC>
vnoremap <silent> <C-S>         <C-C>:update<CR><ESC>
inoremap <silent> <C-S>         <C-O>:update<CR><ESC>
